<a href="https://colab.research.google.com/github/soumyamulgund/Agentic-AI-Application/blob/main/GenAI_2026_Basic_text_processing_using_Scikit_Learn_and_Classifying_Newsgroup_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multi Layer Perceptrons - ASSIGNMENT

#Instructions

1. Click $\texttt{File--> Save a copy in Drive}$ in colab menu bar to save a copy of this file in your personal Google Drive. Then you can start editing this notebook.

2. Alternatively, if you have anaconda installed in your local machine, you can download this file by clicking $\texttt{File --> Download --> Download .ipynb}$ to save a copy of this notebook to your machine. Then you can start editing this notebook.

3. Please read the notebook thoroughly. There are practice problems and exercise problems given.

4. All Exercise problems should be attempted. Practice problems are optional.

5. You can get help for code components from the notebook we discussed on 21st March.

6. Once you are ready with your solutions, click Run --> Run all in the menu bar and make sure that you do not have errors in any of your outputs.

7. Click $\texttt{File-->Print}$ from menu bar and print your solution to a $\texttt{pdf}$ file.

8. Submit the solution as both $\texttt{.ipynb}$ file and $\texttt{pdf}$ file.

#Text Processing with 20 NewsGroup Dataset

In this notebook, first we will learn how to process text data as numerical data and then use the data for classification.

First we will use a popular dataset called 20NewsGroups Dataset.

Details about this dataset can be found at the following link: [Newsgroup Dataset](http://qwone.com/~jason/20Newsgroups/)

In [ ]:
#import package from scikit-learn containing 20newsgroups data
from sklearn.datasets import fetch_20newsgroups

full_train_data_labels = fetch_20newsgroups(subset = 'train') #to download the 20newsgroup dataset

#print the labels in the data
#print(type(full_train_data_labels.target_names)) #uncomment and check the output
print(list(set(full_train_data_labels.target_names)))


['comp.windows.x', 'sci.crypt', 'rec.sport.baseball', 'rec.autos', 'talk.politics.mideast', 'talk.politics.misc', 'sci.electronics', 'rec.motorcycles', 'talk.politics.guns', 'rec.sport.hockey', 'misc.forsale', 'comp.graphics', 'comp.sys.mac.hardware', 'soc.religion.christian', 'talk.religion.misc', 'sci.space', 'sci.med', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'alt.atheism']


The above categories are the different topics of newsitems present in the 20 NewsGroup Dataset.

We will consider two categories below namely: $\texttt{comp.graphics}$ and $\texttt{sci.med}$.

In [ ]:
categories_list = ['comp.graphics', 'sci.med']

#Note that in the statement below, we fetch data concerned with the two categories in categories_list
train_data_labels = fetch_20newsgroups(subset='train',categories=categories_list, shuffle=True)


print(list(set(train_data_labels.target_names)))

#print a few documents and corresponding labels
num_documents = 3
for i in range(num_documents):
  print('Document:')
  print(train_data_labels.data[i])
  print('label:',train_data_labels.target[i])
  print('##########################################################')



['comp.graphics', 'sci.med']
Document:
From: zyeh@caspian.usc.edu (zhenghao yeh)
Subject: Re: Need polygon splitting algo...
Organization: University of Southern California, Los Angeles, CA
Lines: 25
Distribution: world
NNTP-Posting-Host: caspian.usc.edu
Keywords: polygons, splitting, clipping


In article <1qvq4b$r4t@wampyr.cc.uow.edu.au>, g9134255@wampyr.cc.uow.edu.au (Coronado Emmanuel Abad) writes:
|> 
|> The idea is to clip one polygon using another polygon (not
|> necessarily rectangular) as a window.  My problem then is in
|> finding out all the new vertices of the resulting "subpolygons"
|> from the first one.  Is this simply a matter of extending the
|> usual algorithm whereby each of the edges of one polygon is checked
|> against another polygon???  Is there a simpler way??
|> 
|> Comments welcome.
|> 
|> Noel.

	It depends on what kind of the polygons. 
	Convex - simple, concave - trouble, concave with loop(s)
	inside - big trouble.

	Of cause, you can use the box test to av

$\textbf{About converting text features to numerical attributes}$ $\textit{ (From scikit-learn website)}$:

Scikit-learn provides utilities for the most common ways to extract numerical features from text content, namely:


1.   $\textbf{tokenizing}$ strings and giving an integer id for each possible token, for instance by using white-spaces and punctuation as token separators.
2.   $\textbf{counting}$ the occurrences of tokens in each document.
3.   $\textbf{normalizing and weighting}$ with diminishing importance for tokens that occur in majority of samples / documents.


In this scheme, features and samples are defined as follows:

1.   Each individual token occurrence frequency (normalized or not) is treated as a $\textbf{feature}$
2.   The vector of all the token frequencies for a given document is considered a $\textbf{multivariate sample}$.

First, we will consider a very simple dataset that will illustrate the idea of tokenization, counting, normalizing and weighting.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()

In [ ]:
#This is our simple dataset. It has four documents.
corpus = ['This is the first sample document.',
          'This is another document called the second sample document.',
          'And the third sample document.',
          'Is this the first sample document?',
        ]

In [ ]:
X = vectorizer.fit_transform(corpus) #recall: vectorizer is initialized to countvectorizer.
print(type(X))
#print(X)

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:
#unique words obtained from the corpus. Note: All words have lower case letters
print(vectorizer.get_feature_names_out())

['and' 'another' 'called' 'document' 'first' 'is' 'sample' 'second' 'the'
 'third' 'this']


$\textbf{Note:}$ CountVectorizer by default tokenizes string by extracting words of at least 2 letters.

In [ ]:
print(X.toarray()) #Here is where we convert the text data into numerical data. Please understand this conversion process.

[[0 0 0 1 1 1 1 0 1 0 1]
 [0 1 1 2 0 1 1 1 1 0 1]
 [1 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 1 1 0 1 0 1]]


In the above numerical array, we have four rows corresponding to four documents. Each inner array has 12 values, corresponding to the number of unique tokens obtained by  $\texttt{vectorizer.get_feature_names_out()}$.

Now, we note that the values actually correspond to the frequency of each token in the document.

For example:

The second row is $\texttt{[0 1 1 2 0 1 1 1 1 0 1]}$.

This corresponds to the document `This is another document called the second sample document.`

The feature vector $\texttt{[0 1 1 2 0 1 1 1 1 0 1]}$ means the following:



*   the first token $\texttt{and}$ appears zero times (indicated by the first value $\texttt{0}$)
*   the second token $\texttt{another}$ appears once (indicated by the second value $\texttt{1}$)
*   the third token $\texttt{called}$ appears once (indicated by the third value $\texttt{1}$)
*   the fourth token $\texttt{document}$ appears twice (indicated by the fourth value $\texttt{2}$)
*   and so on...




In [ ]:
#This prints the vocabulary of unique tokens in the corpus with a corresponding index.
print(vectorizer.vocabulary_)

{'this': 10, 'is': 5, 'the': 8, 'first': 4, 'sample': 6, 'document': 3, 'another': 1, 'called': 2, 'second': 7, 'and': 0, 'third': 9}


In [ ]:
#to get the feature identifier of a particular word
print(vectorizer.vocabulary_.get('called'))

2


In [ ]:
#we can use the vectorizer object created earlier to encode new sentences
#However if the new sentence contains new words, they would not be added to the vocabulary
vectorizer.transform(['completely new sentence.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
vectorizer.transform(['another new sample document.']).toarray()

array([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
#if we want to rebuild the vectorizer we must include the new documents in corpus
#and then reconstruct again
#Consider this as a practice exercise and try adding new documents to the corpus and rebuild the vocabulary.

In [ ]:
#recall: in our corpus the first document is 'This is the first sample document.',
#and the last document is 'Is this the first sample document?'
print(X.toarray()[0])
print(X.toarray()[-1])

[0 0 0 1 1 1 1 0 1 0 1]
[0 0 0 1 1 1 1 0 1 0 1]


## Bigrams and Trigrams

In the earlier use of $\texttt{CountVectorizer()}$ we considered single-word tokens only. Such single-word token is called $\texttt{unigram}$.

However sequences of words can also be helpful in many cases indicating the relationships between multiple words.

To account for this, we can use a sequence of two words called $\texttt{bigram}$ and a sequence of three words called $\texttt{trigram}$ and so on, and in general a sequence of $n$-words as $\texttt{n-gram}$.

For example, consider the first document in our simple corpus:

`This is the first sample document`

From this we can extract the following bigrams: $\texttt{(This, is)}$, $\texttt{(is, the)}$, $\texttt{(the, first)}$, $\texttt{(first, sample)}$, $\texttt{(sample, document)}$.

Also we can extract the following trigrams: $\texttt{(This, is, the)}$, $\texttt{(is, the, first)}$, $\texttt{(the, first, sample)}$, $\texttt{(first, sample, document)}$.

And the 4-grams are: $\texttt{(This, is, the, first)}$, $\texttt{(is, the, first, sample)}$, $\texttt{(the, first, sample, document)}$.

#Question:  
Suppose a document contains $N$ words in sequence, of the form $(w_1, w_2, w_3, \ldots, w_N)$. Assume that each word is unique. That is $w_i \neq w_j$ when $i \neq j$, where $i,j \in \{1,2,3,\ldots,N\}$. How many unigrams, bigrams, trigrams, 4-grams, and in general $n$-grams can be constructed from such sequence?  


Now we will use $\texttt{CountVectorizer()}$ to consider unigrams and bigrams.

In [ ]:
#To account for the word order we can use bigrams and n-grams containing multiple words as features
#we will build another vectorizer using bigram features now
bigram_vectorizer = CountVectorizer(ngram_range=(1,2)) #consider both unigrams and bigrams

In [ ]:
X_unigram_bigram = bigram_vectorizer.fit_transform(corpus)
print(type(X_unigram_bigram))

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:

print(bigram_vectorizer.get_feature_names_out()) #watch for the bigrams along with unigrams now

['and' 'and the' 'another' 'another document' 'called' 'called the'
 'document' 'document called' 'first' 'first sample' 'is' 'is another'
 'is the' 'is this' 'sample' 'sample document' 'second' 'second sample'
 'the' 'the first' 'the second' 'the third' 'third' 'third sample' 'this'
 'this is' 'this the']


In [ ]:
print(len(bigram_vectorizer.get_feature_names_out()))

27


In [ ]:
bigram_vectorizer.vocabulary_

{'this': 24,
 'is': 10,
 'the': 18,
 'first': 8,
 'sample': 14,
 'document': 6,
 'this is': 25,
 'is the': 12,
 'the first': 19,
 'first sample': 9,
 'sample document': 15,
 'another': 2,
 'called': 4,
 'second': 16,
 'is another': 11,
 'another document': 3,
 'document called': 7,
 'called the': 5,
 'the second': 20,
 'second sample': 17,
 'and': 0,
 'third': 22,
 'and the': 1,
 'the third': 21,
 'third sample': 23,
 'is this': 13,
 'this the': 26}

In [ ]:
#Now the feature vector is based on the dictionary above which has unigrams and bigrams.
X_unigram_bigram.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
        0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 1]])

#Exercise:
Understand the construction of $\texttt{X_unigram_bigram}$.

In [ ]:
#Now let us compare the features of first and last document
print(X_unigram_bigram.toarray()[0])
print(X_unigram_bigram.toarray()[-1])

[0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 0]
[0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1]


#Question:

Compare and contrast the first and last rows of $\texttt{X_unigram_bigram}$ with those of $\texttt{X}$. What do you observe?

In [ ]:
#Exercise: Try to build a vectorizer with unigram, bigram and trigram features

#Weights for vocabulary elements based on frequency of occurence in the corpus

Now we will consider how to weigh the relative importance of each vocabulary element using a frequency based weight.

Note that words like $\texttt{is}$, $\texttt{a}$, $\texttt{the}$ appear frequently in most documents. But appearing multiple times does not make these words significant.

Actually, it's the opposite. In general, one can assume that if a vocabulary element repeatedly appears in many documents multiple times, such a vocabulary element is not very important.

However if a vocabulary element appears multiple times in a particular document, but appears very infrequently in other documents, then that element might be related to the topic discussed in that one document. Hence it can be considered to be important.

The idea of $\textbf{term frequency}$ and $\textbf{inverse document frequency}$ capture this essence.

$\textbf{TF-IDF}:$ The term frequency-inverse document frequency (TF-IDF) re-weighting is useful to reduce the dominance of count based features used for very frequent words (or vocabulary elements) which might not have much significance.

$\textbf{Term Frequency}:$ $\texttt{tf(t,d)}$ denotes the frequency of term (or vocabulary element) $\texttt{t}$ in document $\texttt{d}$.

$\textbf{Inverse Document Frequency}:$ $\texttt{idf(t)}$ is proportional to the inverse of the number of documents containing the term $\texttt{t}$. The formula to compute $\texttt{idf(t)}$ is:

$
\begin{align}
\texttt{idf(t)} = \log \frac{1+n}{1+\texttt{df(t)}} + 1
\end{align}
$

where $n$ denotes the number of documents in the corpus and $\texttt{df(t)}$ denotes the number of documents in the corpus containing term $\texttt{t}$. The addition with $1$ is useful for avoiding numerical issues.

Thus $\textbf{TF-IDF}$ is calculated as: $\texttt{tf-idf(t,d)}=\texttt{tf(t,d)} \times \texttt{idf(t)}$.  

After composing the vector for each document, the vectors are normalized so that they are of unit length in terms of Euclidean norm.

In [ ]:
corpus_2 = [ 'The boy came to the school in the morning by the bus.',
             'He took his book and wrote in the book using his pencil.',
             'He played the game using the ball.',
             'He took his bag, left the school by the bus and reached his home.',
             ]

In [ ]:
#a simple count based vectorizer gives too much significance to words like "the", "his"
vectorizer_corpus_2 = CountVectorizer()

In [ ]:
X_corpus_2 = vectorizer_corpus_2.fit_transform(corpus_2)

In [ ]:
print(vectorizer_corpus_2.get_feature_names_out())
print('num features:',len(vectorizer_corpus_2.get_feature_names_out()))

['and' 'bag' 'ball' 'book' 'boy' 'bus' 'by' 'came' 'game' 'he' 'his'
 'home' 'in' 'left' 'morning' 'pencil' 'played' 'reached' 'school' 'the'
 'to' 'took' 'using' 'wrote']
num features: 24


In [ ]:
print(vectorizer_corpus_2.vocabulary_)

{'the': 19, 'boy': 4, 'came': 7, 'to': 20, 'school': 18, 'in': 12, 'morning': 14, 'by': 6, 'bus': 5, 'he': 9, 'took': 21, 'his': 10, 'book': 3, 'and': 0, 'wrote': 23, 'using': 22, 'pencil': 15, 'played': 16, 'game': 8, 'ball': 2, 'bag': 1, 'left': 13, 'reached': 17, 'home': 11}


In [ ]:
X_corpus_2.toarray()

array([[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 4, 1, 0,
        0, 0],
       [1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0,
        1, 0],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1,
        0, 0]])

Note that in $\texttt{X_corpus_2}$ we have large values for more frequent terms like $\texttt{the}$, $\texttt{his}$, etc.

Instead of a simple count based vectorizer, we will use a TF-IDF based feature vector construction.

In [ ]:
#Let us transform the features using a tf-idf based weight scheme
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()

In [ ]:
tfidf_X_corpus_2 = tfidf_transformer.fit_transform(X_corpus_2) #Note: We are using X_corpus_2 to fit a TF-IDF transform.

In [ ]:
print(tfidf_X_corpus_2.toarray())

[[0.         0.         0.         0.         0.30367981 0.23942465
  0.23942465 0.30367981 0.         0.         0.         0.
  0.23942465 0.         0.30367981 0.         0.         0.
  0.23942465 0.63389088 0.30367981 0.         0.         0.        ]
 [0.23096381 0.         0.         0.58589662 0.         0.
  0.         0.         0.         0.18698511 0.46192763 0.
  0.23096381 0.         0.         0.29294831 0.         0.
  0.         0.15287258 0.         0.23096381 0.23096381 0.29294831]
 [0.         0.         0.44201611 0.         0.         0.
  0.         0.         0.44201611 0.28213316 0.         0.
  0.         0.         0.         0.         0.44201611 0.
  0.         0.46132469 0.         0.         0.34849058 0.        ]
 [0.23673759 0.30027162 0.         0.         0.         0.23673759
  0.23673759 0.         0.         0.19165948 0.47347519 0.30027162
  0.         0.30027162 0.         0.         0.         0.30027162
  0.23673759 0.31338837 0.         0.2367

Note that in $\texttt{tfidf_X_corpus_2}$ the weights of more frequent (appearing multiple times in most documents in the corpus) non-important vocabulary elements have been reduced.

In [ ]:
#check if each row has unit Euclidean norm
import numpy as np
X1 = tfidf_X_corpus_2.toarray()
for i in range(len(X1)):
  print(np.linalg.norm(X1[i]))

1.0
1.0000000000000002
1.0
0.9999999999999998


We can now use this idea of Tf-IDF based weight scheme to construct feature vectors for 20 NewsGroup Data.

$\textbf{Getting back to 20 Newsgroups data:}$ We now consider the text processing of the data corresponding to two categories $\texttt{comp.graphics}$, $\texttt{sci.med}$.  

In [ ]:
print('num documents:', len(train_data_labels.data))

num documents: 1178


In [ ]:
data_20newsgroups_vectorizer = CountVectorizer() #we consider only unigrams here

In [ ]:
X_train_20newsgroups = data_20newsgroups_vectorizer.fit_transform(train_data_labels.data)

In [ ]:
num_features = len(data_20newsgroups_vectorizer.get_feature_names_out())
print('num features:', num_features)

num features: 24614


In [ ]:
print(X_train_20newsgroups.toarray().shape)

(1178, 24614)


In [ ]:
num_samples = X_train_20newsgroups.toarray().shape[0]
print('num samples:', num_samples)

num samples: 1178


In [ ]:
y_train_20newsgroups = train_data_labels.target
print(y_train_20newsgroups.shape)

(1178,)


#Exercise



Shuffle and split $\texttt{(X_train_20newsgroups, y_train_20newsgroups)}$ into 80\% which you will use for training, and 20\% which you will use for validation.

Use specific names for these partitions.

In [ ]:
#Create Data partitions for train, val partitions

Create Data loaders for loading the train and val data partitions.

In [ ]:
#Code for data loaders

Construct a simple MLP to classify the samples into the two categories.

In [ ]:
#your network architecture and forward() function goes here
import torch
class MyMLP(torch.nn.Module):
        pass

In [ ]:
#Create a model object
#model = ???

#Set up a loss function
#criterion = ???

#Set up an optimizer
#optimizer = ???

In [ ]:
#set model to train mode
#model.train()

#set number of epochs for training
#num_epochs = ??

#Write code for training your network using mini-batch optimization


Plot the loss and accuracy values obtained on train and val split.

In [ ]:
import matplotlib.pyplot as plt
#plt.plot(??)
#plt.ylabel('loss')
#plt.xlabel('Epochs')
#plt.show()

#Evaluate your model on test data, that is already provided in the original data source.

In [ ]:
test_data_labels = fetch_20newsgroups(subset='test',categories=categories_list, shuffle=True)

X_test_20newsgroups = data_20newsgroups_vectorizer.transform(test_data_labels.data) # we only use transform
print(X_test_20newsgroups.shape)
y_test_20newsgroups = test_data_labels.target

num_test_samples = X_test_20newsgroups.toarray().shape[0]
print('num test samples:',num_test_samples)



(785, 24614)
num test samples: 785


Set up a data loader for the test data.

In [ ]:
#Data loader for test

Use the trained model to evaluate accuracy, F1, Precision, Recall on the Test Data

In [ ]:
#set the neural net model to eval mode for testing
#model.eval()

#Write code for evaluation


# Evaluate the model on another data corpus.

In [ ]:
newsgroup_test_corpus = ['The monitor in operation theatre has some snag',
                         'What is the RAM size used in the PC?',
                         'RBC and Haemoglobin are below normal.',
                         'Renal disease is on the rise.',
                         'Neurologists believe that this case is rare.']
X_test_corpus = data_20newsgroups_vectorizer.transform(newsgroup_test_corpus) # we only use transform
print(X_test_corpus.shape)

num_test_samples = X_test_corpus.toarray().shape[0]
print('num test samples:',num_test_samples)


# model.eval()

# x_test = torch.FloatTensor(X_test_corpus.toarray())

# y_test_pred = model(x_test)

# y_test_pred_cpu = y_test_pred.squeeze().detach().cpu().numpy()
# y_test_pred_cpu = np.multiply(y_test_pred_cpu>0.5,1)

# print('predictions:')
# print(y_test_pred_cpu)


(5, 24614)
num test samples: 5


$\large{\textbf{Exercise Problems}}$
###Attempt all Exercise Problems

1. (a) Use unigram and bigram features and perform training using an appropriate feed forward network (or) MLP. Compute train set, val set and test set accuracy, F1 score, Precision, Recall and Confusion matrix.
(b) Use unigram, bigram and trigram features in the code above and perform training using an appropriate feed forward network. Compute train set, val set and test set accuracy, F1 score, Precision, Recall and Confusion matrix.
(c) Compare and contrast the train set and test set performance metrics for parts (a) and (b) with those obtained in the code above where we used only unigrams. Discuss.

2. Select your $k$ favorite classes of newsgroups and perform multi-class classification training using the feed forward network (by modifying the output layer). Use unigram, bigram and trigram features. Compute train set, val set and test set accuracy, F1 score, Precision, Recall and Confusion matrix.
   

#Practice Problems

3. Use other classification techniques like SVM, decision tree, random forest, KNN for the classification problem above using (a) unigram, (b) unigram and bigram (c) unigram, bigram and trigram features. In each case, compute the train set, val set and test set accuracy, F1 score, Precision, recall and confusion matrix. Compare your results with those obtained from feed forward network above in Question 1.

4. Use other classification techniques like SVM, decision tree, random forests, KNN for the multi-class classification problem and compute the train set, val set and test set accuracy, F1 score, Precision, recall and confusion matrix. Compare your results with those obtained from feed forward network above in Question 2.
